### ISSUE TITLE
java.io.IOException: Failed to delete original file 'd:\oss-apk-repository\201804091314.apk.tmp'

### ISSUE THREAD

**Issue by John-zero** [aliyun/aliyun-oss-java-sdk#136]
V3.1.0 的版本, Windows 和 Linux 系统下测试频繁出现这个异常, 怎么解决?
java.io.IOException: Failed to delete original file 'd:\xingfei-repository\xproject-support\xproject-file-repository\201804091314\201804091314.apk.tmp'
	at com.aliyun.oss.internal.OSSDownloadOperation.moveFile(OSSDownloadOperation.java:611)
	at com.aliyun.oss.internal.OSSDownloadOperation.renameTo(OSSDownloadOperation.java:590)
	at com.aliyun.oss.internal.OSSDownloadOperation.downloadFileWithCheckpoint(OSSDownloadOperation.java:361)
	at com.aliyun.oss.internal.OSSDownloadOperation.downloadFile(OSSDownloadOperation.java:315)
	at com.aliyun.oss.OSSClient.downloadFile(OSSClient.java:1180)
	at com.shop.service.GameSubPackageService.OSSDownloadFile(GameSubPackageService.java:250)

**Comment by Shallwewu** [comment]
> V3.1.0 的版本, Windows 和 Linux 系统下测试频繁出现这个异常, 怎么解决?
> 看异常提示是 SDK 内部处理异常...
> 有遇到过类似的问题的吗?
> java.io.IOException: Failed to delete original file 'd:\oss-apk-repository\201804091314.apk.tmp'
> at com.aliyun.oss.internal.OSSDownloadOperation.moveFile(OSSDownloadOperation.java:611)
> at com.aliyun.oss.internal.OSSDownloadOperation.renameTo(OSSDownloadOperation.java:590)
> at com.aliyun.oss.internal.OSSDownloadOperation.downloadFileWithCheckpoint(OSSDownloadOperation.java:361)
> at com.aliyun.oss.internal.OSSDownloadOperation.downloadFile(OSSDownloadOperation.java:315)
> at com.aliyun.oss.OSSClient.downloadFile(OSSClient.java:1180)
> at com.shop.service.GameSubPackageService.OSSDownloadFile(GameSubPackageService.java:250)

应该是没有权限操作你的目录，这里是指删除和创建临时文件之类失败。

**Comment by liuyu-struggle** [comment]
还有哪位大哥遇到这个问题吗，我这边也遇到这个问题了，不过不是必现的问题，是偶尔出现的，期待有相关的解答
