### ISSUE TITLE
返回结果无效，无法解析怎么回事，出现概率大概十分之一，上传图片大点就很可能出现，比如300kb

### ISSUE THREAD

**Issue by xinwii** [aliyun/aliyun-oss-java-sdk#144]
22:11:23.567 [main] WARN com.aliyun.oss - [Server]Unable to execute HTTP request: 返回结果无效，无法解析。
[ErrorCode]: InvalidResponse
[RequestId]: null
[HostId]: null
Exception in thread "main" com.aliyun.oss.OSSException: 返回结果无效，无法解析。
[ErrorCode]: InvalidResponse
[RequestId]: null
[HostId]: null
	at com.aliyun.oss.common.utils.ExceptionFactory.createOSSException(ExceptionFactory.java:109)
	at com.aliyun.oss.common.utils.ExceptionFactory.createInvalidResponseException(ExceptionFactory.java:91)
	at com.aliyun.oss.common.utils.ExceptionFactory.createInvalidResponseException(ExceptionFactory.java:81)
	at com.aliyun.oss.internal.OSSErrorResponseHandler.handle(OSSErrorResponseHandler.java:71)
	at com.aliyun.oss.common.comm.ServiceClient.handleResponse(ServiceClient.java:248)
	at com.aliyun.oss.common.comm.ServiceClient.sendRequestImpl(ServiceClient.java:130)
	at com.aliyun.oss.common.comm.ServiceClient.sendRequest(ServiceClient.java:68)
	at com.aliyun.oss.internal.OSSOperation.send(OSSOperation.java:94)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:149)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:113)
	at com.aliyun.oss.internal.OSSObjectOperation.writeObjectInternal(OSSObjectOperation.java:907)
	at com.aliyun.oss.internal.OSSObjectOperation.putObject(OSSObjectOperation.java:148)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:475)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:457)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:451)

**Comment by xinwii** [comment]
把自定义域名换成了阿里的oss域名，可以了，自定义域名有bug吧？

**Comment by fukai7722** [comment]
我也遇到了，官方要不要解决一下

**Comment by cyulong9526** [comment]
我也遇到这个问题了，是Bucket 域名 的问题么？

**Comment by xinwii** [comment]
> 我也遇到这个问题了，是Bucket 域名 的问题么？

把自定义域名换成了阿里的oss域名

**Comment by huiguangjun** [comment]
1. sdk 收到的响应内容 不是 oss 返回的合法格式，所以无法解析。
2. 如果使用了自定义域名，请确保该域名已经解析到 该bucket 对应的 虚拟域名上

**Comment by li-xiaojun** [comment]
目前是2022年12月13日，仍然存在这个bug，我的最新版本，3.15.2，而且没有使用自定义域名

**Comment by LzsLC** [comment]
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.1</version>
</dependency>
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>activation</artifactId>
    <version>1.1.1</version>
</dependency>

<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.3</version>
</dependency>
