### ISSUE TITLE
There is a com.aliyun.oss.InconsistentException in aliyun_sdk_oss 2.8.1 with pinponit 1.7.3 

### ISSUE THREAD

**Issue by reymont** [aliyun/aliyun-oss-java-sdk#156]
pinpoint=1.7.3
com.aliyun.oss:aliyun-sdk-oss=2.8.1

The shell is:
```
java -server -Xmx300m -javaagent:/pinpoint-agent-1.7.3/pinpoint-bootstrap-1.7.3.jar \
    -Dpinpoint.agentId=PoiApplication \
    -Dpinpoint.applicationName=PoiApplication \
    -Dfile.encoding=UTF-8 -jar jego-managerportal-poi-5.2.0.2.jar \
    --spring.cloud.config.uri=http://configuration-service.dev03.svc.cluster.local:8888

```

The client invoke:
```java
public OSSClient client;
client = new OSSClient(endpoint, accessKeyId, accessKeySecret);
result = client.putObject(accessService.defaultBucketName, key, content, meta);
```

got the error:
```log
com.aliyun.oss.InconsistentException: InconsistentException 
[RequestId]: 5BA9B6486D740B8A2FCECDA0
[ClientChecksum]: 711120333747229212
[ServerChecksum]: 9180275173150973139
	at com.aliyun.oss.internal.OSSUtils.checkChecksum(OSSUtils.java:484)
	at com.aliyun.oss.internal.OSSObjectOperation.putObject(OSSObjectOperation.java:154)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:473)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:455)
	at com.cmi.jego.poi.action.BaseController.putObject(BaseController.java:321)
	at com.cmi.jego.poi.action.BaseController.uploadFileOSS(BaseController.java:255)
```

**Comment by reymont** [comment]
其实也没有最终解决，只是发现了问题，即aliyun_sdk_oss_2.8.1与pinpoint 1.7.3 中的httpclient版本不兼容，pinpoint 1.7.3对http响应做了修改，导致 oss checksum失败。最简单的方式是 屏蔽 pinpoint对httpclient的采样，profiler.apache.httpclient* = false。
