### ISSUE TITLE
OssClient.putObject被hang

### ISSUE THREAD

**Issue by dczz** [aliyun/aliyun-oss-java-sdk#162]
跑到500 800的就被hangs了
`
伪代码大概这样：
List<String> arr = new ArrayList<String>();
for (int i =0;i<1000;i++){
  OssClient ossClient = new OssClient();
  try {
    ossClient.putObject(bucketName,key,is);
  } catch (Exception e){
    serr(e);
  } finally {
    ossClient.shutdown();
  }
  arr.add(key);
}

堆栈如下：

"main" #1 prio=5 os_prio=0 tid=0x0000000002a8d800 nid=0x3224 runnable [0x0000000002a7c000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x0000000770d73270> (a java.io.BufferedInputStream)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	- locked <0x0000000770d76418> (a sun.net.www.http.KeepAliveStream)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x0000000770d77048> (a java.io.BufferedInputStream)
	at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.aliyun.oss.common.comm.io.ChunkedInputStreamEntity$ReleasableInputStreamEntity.writeTo(ChunkedInputStreamEntity.java:150)
	at com.aliyun.oss.common.comm.io.ChunkedInputStreamEntity.writeTo(ChunkedInputStreamEntity.java:88)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:160)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.aliyun.oss.common.comm.DefaultServiceClient.sendRequestCore(DefaultServiceClient.java:124)
	at com.aliyun.oss.common.comm.ServiceClient.sendRequestImpl(ServiceClient.java:133)
	at com.aliyun.oss.common.comm.ServiceClient.sendRequest(ServiceClient.java:70)
	at com.aliyun.oss.internal.OSSOperation.send(OSSOperation.java:94)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:156)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:113)
	at com.aliyun.oss.internal.OSSObjectOperation.writeObjectInternal(OSSObjectOperation.java:816)
	at com.aliyun.oss.internal.OSSObjectOperation.putObject(OSSObjectOperation.java:147)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:485)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:469)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:463)`

**Comment by GDongYang** [comment]
怎么解决的
