### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by liaohuqiu** [aliyun/aliyun-oss-java-sdk#209]
```
Exception in thread "pool-2-thread-1" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.aliyun.oss.internal.OSSErrorResponseHandler.handle(OSSErrorResponseHandler.java:66)
	at com.aliyun.oss.common.comm.ServiceClient.handleResponse(ServiceClient.java:248)
	at com.aliyun.oss.common.comm.ServiceClient.sendRequestImpl(ServiceClient.java:130)
	at com.aliyun.oss.common.comm.ServiceClient.sendRequest(ServiceClient.java:68)
	at com.aliyun.oss.internal.OSSOperation.send(OSSOperation.java:94)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:149)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:113)
	at com.aliyun.oss.internal.OSSObjectOperation.getSimplifiedObjectMeta(OSSObjectOperation.java:354)
	at com.aliyun.oss.internal.OSSObjectOperation.doesObjectExist(OSSObjectOperation.java:737)
	at com.aliyun.oss.OSSClient.doesObjectExist(OSSClient.java:634)
	at com.aliyun.oss.OSSClient.doesObjectExist(OSSClient.java:612)
	at kxi.vendors.aliyun.OSS.exist(OSS.java:62)
	at kxi.apps.event.FileStore.downloadFromOSSAndUnzip(FileStore.java:119)
	at kxi.apps.event.FileStore.downloadFromOSSThenUnzipAndJsonDecode(FileStore.java:98)
	at kxi.apps.event.EventDataProvider.loadEventData(EventDataProvider.java:66)
	at kxi.apps.event.EventDataProvider.loadData(EventDataProvider.java:61)
	at kxi.apps.event.EventDataProvider.start(EventDataProvider.java:57)
	at kxi.apps.event.EventServant$1.run(EventServant.java:34)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 21 more
```

JDK:

```
(py2) huqiu:kxi huqiu$ java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

**Comment by liaohuqiu** [comment]
It is JDK 11 compatibility issue. See #210
