### ISSUE TITLE
使用OSS的Range下载是否支持CRC校验？

### ISSUE THREAD

**Issue by cheyang** [aliyun/aliyun-oss-java-sdk#256]
通过指定OSS Object的Range调用下载

```java
// OSSObject object = ossClient.getObject(bucketName, key);
            GetObjectRequest request = new GetObjectRequest(bucketName, key);

            long startPos = 1, endPos = 3;
            request.setRange(startPos, endPos);

            File file = new File(key);
//            file.getParentFile().mkdirs();

            meta = ossClient.getObject(request, file);
```

结果会报：

```
Exception in thread "main" com.aliyun.oss.InconsistentException: InconsistentException 
[RequestId]: 5D9ECBF053856F3239139FE5
[ClientChecksum]: 3468660410647627105
[ServerChecksum]: 999854452271583453
	at com.aliyun.oss.internal.OSSUtils.checkChecksum(OSSUtils.java:479)
	at com.aliyun.oss.internal.OSSObjectOperation.getObject(OSSObjectOperation.java:408)
	at com.aliyun.oss.OSSClient.getObject(OSSClient.java:559)
	at com.aliyun.osscli.GetOSSObjectFile.main(GetOSSObjectFile.java:94)
```

经过排查发现不论下载的range如何变化，server端的CRC都是999854452271583453。 想知道我们对于CRC校验的支持是仅仅限于完整OSS对象吗？

**Comment by huiguangjun** [comment]
response header 的 crc 字段 是对整个文件的。 range 请求时不支持 crc校验。
