### ISSUE TITLE
并发下载情况下出现ERROR：Premature end of Content-Length delimited message body 

### ISSUE THREAD

**Issue by cheyang** [aliyun/aliyun-oss-java-sdk#259]
通过框架并发调用oss.getObject的stream读取文件，调用时间仅为15ms

```
2019-10-14 02:08:26,265 WARN  AbstractReadHandler - Exception occurred while reading data for read request alluxio.worker.grpc.BlockReadRequest@6a30091f, and it took 15 ms
2019-10-14 02:08:26,266 WARN  AbstractReadHandler - Exception occurred while reading data for read request alluxio.worker.grpc.BlockReadRequest@6a30091f.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 33554432; received: 31451830
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.aliyun.oss.event.ProgressInputStream.read(ProgressInputStream.java:118)
        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at alluxio.underfs.MultiRangeObjectInputStream.read(MultiRangeObjectInputStream.java:80)
        at io.netty.buffer.UnsafeByteBufUtil.setBytes(UnsafeByteBufUtil.java:454)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:278)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1118)
        at alluxio.worker.block.UnderFileSystemBlockReader.transferTo(UnderFileSystemBlockReader.java:223)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:110)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:70)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.runInternal(AbstractReadHandler.java:326)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.run(AbstractReadHandler.java:293)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.run(BlockReadHandler.java:70)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

可以看到类似的问题，怀疑是服务器端的问题：
https://github.com/aliyun/aliyun-oss-java-sdk/issues/78
https://stackoverflow.com/questions/23152816/premature-end-of-content-length-delimited-message-body-expected

**Comment by wuuJiawei** [comment]
+1

**Comment by starlightparade** [comment]
请问楼主这个问题得到解决了吗？

**Comment by wangdiskater** [comment]
+1

**Comment by starlightparade** [comment]
> +1

试过了不同的读取时间，达到30s左右就会报错，并不是说达到设定的timeout值60s才会有报错。最后还是通过减少读取的时间解决了这个问题。

**Comment by chang1sun** [comment]
+1

**Comment by wangdiskater** [comment]
您好，我已经收到您发来的邮件，我会尽快看完，谢谢您！
