### ISSUE TITLE
通过流的方式，传输大文件，每次都卡在22224154624（20G）左右，这是有什么限制吗

### ISSUE THREAD

**Issue by cherishzhao** [aliyun/aliyun-oss-java-sdk#298]
错误信息如下：

com.aliyun.oss.ClientException: Failed to reset the request input stream:
[ErrorCode]: Unknown
[RequestId]: Unknown
        at com.aliyun.oss.common.comm.ServiceClient.sendRequestImpl(ServiceClient.java:114) ~[aliyun-sdk-oss-3.6.0.jar!/:na]
        at com.aliyun.oss.common.comm.ServiceClient.sendRequest(ServiceClient.java:70) ~[aliyun-sdk-oss-3.6.0.jar!/:na]
        at com.aliyun.oss.internal.OSSOperation.send(OSSOperation.java:83) ~[aliyun-sdk-oss-3.6.0.jar!/:na]
        at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:145) ~[aliyun-sdk-oss-3.6.0.jar!/:na]
        at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:102) ~[aliyun-sdk-oss-3.6.0.jar!/:na]
        at com.aliyun.oss.internal.OSSObjectOperation.writeObjectInternal(OSSObjectOperation.java:1125) ~[aliyun-sdk-oss-3.6.0.jar!/:na]
        at com.aliyun.oss.internal.OSSObjectOperation.putObject(OSSObjectOperation.java:130) ~[aliyun-sdk-oss-3.6.0.jar!/:na]
        at com.aliyun.oss.OSSClient.putObject(OSSClient.java:494) ~[aliyun-sdk-oss-3.6.0.jar!/:na]

**Comment by huiguangjun** [comment]
putObject 接口最大只支持 5G 的数据上传. 

如果要上传大于5G的,请使用分片上传接口, 或者 sdk 封装 的断点上传接口.
