### ISSUE TITLE
error response in listing objects

### ISSUE THREAD

**Issue by samunbest** [aliyun/aliyun-oss-java-sdk#333]
version:3.10.0

com.aliyun.oss.OSSException: 返回结果无效，无法解析。
[ErrorCode]: InvalidResponse
[RequestId]: 5F2E56B3B766D33534D252D6
[HostId]: null
[ResponseError]:
[Document:  No DOCTYPE declaration, Root is [Element: <ListBucketResult/>]]: Error on line 9527: 字符引用 "&#
	at com.aliyun.oss.common.utils.ExceptionFactory.createOSSException(ExceptionFactory.java:110)
	at com.aliyun.oss.common.utils.ExceptionFactory.createInvalidResponseException(ExceptionFactory.java:92)
	at com.aliyun.oss.common.utils.ExceptionFactory.createInvalidResponseException(ExceptionFactory.java:81)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:150)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:102)
	at com.aliyun.oss.internal.OSSBucketOperation.listObjects(OSSBucketOperation.java:463)
	at com.aliyun.oss.OSSClient.listObjects(OSSClient.java:461)
	at com.fumasoft.service.api.MXHelper.job.CleanExpiredMaillogsJob.execute(CleanExpiredMaillogsJob.java:68)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by huiguangjun** [comment]
对象名字含有特殊字符, 
可以参考  https://help.aliyun.com/document_detail/84841.html?spm=a2c4g.11174283.6.848.7acf7da2hpabpO 中的  指定文件名称编码
