### ISSUE TITLE
关于"javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.EventFactory not found"的报错

### ISSUE THREAD

**Issue by kenny-qiao** [aliyun/aliyun-oss-java-sdk#389]
### 版本
'org.hibernate:hibernate-core:5.4.18.Final'
'com.aliyun.oss:aliyun-sdk-oss:3.13.2'

### 错误
项目引入OSS的Java SDK后，出现如下报错，目前定位到出错位置在`stax:stax-api:1.0.1`，暂时先通过`exclude`排除间接依赖的方式解决了。这里提个Issue标记下。

```
Caused by: javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.EventFactory not found
        at javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
        at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:178)
        at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
        at javax.xml.stream.XMLEventFactory.newInstance(XMLEventFactory.java:30)
        at org.hibernate.boot.jaxb.internal.MappingBinder.<init>(MappingBinder.java:40)
        at org.hibernate.boot.spi.XmlMappingBinderAccess.<init>(XmlMappingBinderAccess.java:43)
        at org.hibernate.boot.MetadataSources.getXmlMappingBinderAccess(MetadataSources.java:98)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.prepare(MetadataBuildingProcess.java:101)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:254)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:168)
        at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:32)
        at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:89)
        at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilder(HibernatePersistenceProvider.java:166)
        at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:141)
```

### 解决方案
```
implementation {
    exclude group: 'stax', module: 'stax-api'
}
```

**Comment by li-xiaojun** [comment]
+1
