### ISSUE TITLE
Caused by: java.net.SocketException: Connection reset 不知道什么原因？

### ISSUE THREAD

**Issue by yovenny** [aliyun/aliyun-oss-java-sdk#46]
Exception in thread "main" com.aliyun.oss.ClientException: SocketException
    at com.aliyun.oss.common.utils.ExceptionFactory.createNetworkException(ExceptionFactory.java:71)
    at com.aliyun.oss.common.comm.DefaultServiceClient.sendRequestCore(DefaultServiceClient.java:128)
    at com.aliyun.oss.common.comm.ServiceClient.sendRequestImpl(ServiceClient.java:123)
    at com.aliyun.oss.common.comm.ServiceClient.sendRequest(ServiceClient.java:68)
    at com.aliyun.oss.internal.OSSOperation.send(OSSOperation.java:94)
    at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:149)
    at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:113)
    at com.aliyun.oss.internal.OSSObjectOperation.writeObjectInternal(OSSObjectOperation.java:674)
    at com.aliyun.oss.internal.OSSObjectOperation.putObject(OSSObjectOperation.java:134)
    at com.aliyun.oss.OSSClient.putObject(OSSClient.java:554)
    at com.yovenny.girlhunter.util.OSSClientHelper.upload(OSSClientHelper.java:48)
    at com.yovenny.girlhunter.upload.UploadMain.upload(UploadMain.java:63)
    at com.yovenny.girlhunter.upload.UploadMain.main(UploadMain.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:154)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at sun.net.www.MeteredStream.read(MeteredStream.java:134)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at com.aliyun.oss.event.ProgressInputStream.read(ProgressInputStream.java:116)
    at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at com.aliyun.oss.event.ProgressInputStream.read(ProgressInputStream.java:116)
    at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at com.aliyun.oss.event.ProgressInputStream.read(ProgressInputStream.java:116)
    at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at com.aliyun.oss.event.ProgressInputStream.read(ProgressInputStream.java:116)
    at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
    at java.io.FilterInputStream.read(FilterInputStream.java:107)
    at com.aliyun.oss.common.comm.io.ChunkedInputStreamEntity$ReleasableInputStreamEntity.writeTo(ChunkedInputStreamEntity.java:147)
    at com.aliyun.oss.common.comm.io.ChunkedInputStreamEntity.writeTo(ChunkedInputStreamEntity.java:87)
    at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
    at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
    at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at com.aliyun.oss.common.comm.DefaultServiceClient.sendRequestCore(DefaultServiceClient.java:125)
    ... 16 more

具体代码：

public static void buildClient(){
        if(client==null) client= new OSSClient(endpoint, accessKeyId, accessKeySecret);
    }

```
//上传网络流
public static void upload(String url,String key){
    buildClient();
    if(isUpload) {
        // Object是否存在
        boolean found = client.doesObjectExist(bucketName, key);
        if(found)return;
        InputStream inputStream ;
        try {
            inputStream = new URL(url).openStream();
            PutObjectRequest putObjectRequest=new PutObjectRequest(bucketName, key, inputStream)
                    .withProgressListener(new PutObjectProgressListener());
            client.putObject(putObjectRequest);
            inputStream.close();
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("----------------upload error:"+url);
        }
    }
}
```

**Comment by baiyubin** [comment]
原因是：OSS的客户端与服务器的连接如果一分钟没有数据交换，服务器会关闭连接，客户端再去收发数据就会报上述错误。请检查上传/或者下载的数据流速度是不是很慢，引起了服务器的关闭连接。OSS服务器端的socket buffer是256KB。

**Comment by EirtureLiu** [comment]
@baiyubin 请问一下这个 ”一分钟“ 限定的时间可以修改吗？或者有什么其他办法处理，网速特别慢情况下 上传/下载 服务端会关闭连接的问题呢？
