### ISSUE TITLE
本地上传可以 为什么发服务器就报错呢？

### ISSUE THREAD

**Issue by dayuange123** [aliyun/aliyun-oss-java-sdk#546]
com.aliyun.oss.ClientException: Connection error due to: Connection pool shut down
[ErrorCode]: Unknown
[RequestId]: Unknown
	at com.aliyun.oss.common.comm.ServiceClient.sendRequestImpl(ServiceClient.java:172)
	at com.aliyun.oss.common.comm.ServiceClient.sendRequest(ServiceClient.java:71)
	at com.aliyun.oss.internal.OSSOperation.send(OSSOperation.java:134)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:192)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:153)
	at com.aliyun.oss.internal.OSSObjectOperation.writeObjectInternal(OSSObjectOperation.java:1195)
	at com.aliyun.oss.internal.OSSObjectOperation.putObject(OSSObjectOperation.java:130)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:612)
	at com.zhangkaixu.secret.party.basic.sinking.resources.infrastructure.acl.AliyunCosConfigService.uploadFile(AliyunCosConfigService.java:84)
	at com.zhangkaixu.secret.party.basic.sinking.resources.infrastructure.ResourceUploadServiceProvider.uploadResource(ResourceUploadServiceProvider.java:52)
	at com.zhangkaixu.secret.party.basic.sinking.resources.applic

**Comment by dayuange123** [comment]
PutObjectRequest putObjectRequest = new PutObjectRequest(bucketName, key, inputStream);
			// 上传文件。
			PutObjectResult result = ossClient.putObject(putObjectRequest);


OssProperties.Aliyun aliyun = ossProperties.getAliyun();
		STSAssumeRoleSessionCredentialsProvider credentialsProvider = CredentialsProviderFactory.newSTSAssumeRoleSessionCredentialsProvider(
				aliyun.getRegionId(), aliyun.getAccessKey(), aliyun.getSecretKey(),
				aliyun.getRoleArn());

		// 创建ClientBuilderConfiguration实例。
		ClientBuilderConfiguration conf = new ClientBuilderConfiguration();

		// 创建OSSClient实例。
		this.ossClient = new OSSClientBuilder().build(aliyun.getEndpoint(), credentialsProvider, conf);

**Comment by woxinfeixiang233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dayuange123** [comment]
`OssProperties.Aliyun aliyun = ossProperties.getAliyun();
		STSAssumeRoleSessionCredentialsProvider credentialsProvider = CredentialsProviderFactory.newSTSAssumeRoleSessionCredentialsProvider(
				aliyun.getRegionId(), aliyun.getAccessKey(), aliyun.getSecretKey(),
				aliyun.getRoleArn());

		// 创建ClientBuilderConfiguration实例。
		ClientBuilderConfiguration conf = new ClientBuilderConfiguration();

		// 创建OSSClient实例。
		this.ossClient = new OSSClientBuilder().build(aliyun.getEndpoint(), credentialsProvider, conf);`

**Comment by dayuange123** [comment]
PutObjectRequest putObjectRequest = new PutObjectRequest(bucketName, key, inputStream);
			// 上传文件。
			PutObjectResult result = ossClient.putObject(putObjectRequest);

**Comment by dayuange123** [comment]
好像是刚发布上去可以 ，过一段时间就坏了

**Comment by balckduck** [comment]
是怎么解决的呢
